### ISSUE TITLE
Don't print empty lines on valid Markdown

### ISSUE THREAD

**Issue by adriangrigore** [igorshubovych/markdownlint-cli#10]
When running `markdownlint-cli` on an valid `.md` file, it prints an empty line. I think it's a good idea to have it output nothing (if it has nothing to output of course).

Having taken a quick look at the source code I'm not sure  if this is a `markdownlint` or `markdownlint-cli` related issue.

https://github.com/DavidAnson/markdownlint/issues/30

**Comment by DavidAnson** [comment]
Looking briefly at the code, I think the issue is with how `printResult` handles the case `!hasErrors`. lintResult.toString() will be empty if I recall correctly, so `console.log` of that will output an empty line.

**Comment by adriangrigore** [comment]
Does it have to print anything if there are no errors?
