### ISSUE TITLE
MD044 replaces too much content

### ISSUE THREAD

**Issue by alexbuckgit** [igorshubovych/markdownlint-cli#100]
Creating as a new issue (per the request made in comments for issue # 98):

If I include ".NET" as a value in the MD044 names parameter, then run markdownlint at the command line with the --fix parameter on a file containing this line:

Check (**myserver.mydomain.net**) for failure.
It replaces the entire parenthetical phrase, like this:

Check (.NET) for failure.

**Comment by DavidAnson** [comment]
Thanks! Example to reproduce the issue here: https://github.com/igorshubovych/markdownlint-cli/issues/98#issuecomment-643559112

**Comment by DavidAnson** [comment]
Fixed in the library by https://github.com/DavidAnson/markdownlint/commit/e696960aab3c69ba7be2c71cbd74de071ab083bb for the next release.

**Comment by DavidAnson** [comment]
Fixed in `0.23.2`, just published.
