### ISSUE TITLE
Document the configuration parameters available

### ISSUE THREAD

**Issue by ForNeVeR** [igorshubovych/markdownlint-cli#101]
Currently, all I know about the accepted configuration parameters from the README is that this project is supposed to support rules from some `markdownlint` package (which seems to be deleted from GitHub) and that there's a [test configuration file](https://github.com/igorshubovych/markdownlint-cli/blob/276b78ad6a5aa8d243dc4a8b87e3d275187a70eb/test/test-config.json) with three parameters available. There's also a link to some "[style folder](https://github.com/DavidAnson/markdownlint/tree/master/style)", which is deleted, too.

Does this project support any additional parameters aside from these three? What does these three mean? (I mean, `MD002: true` doesn't tell me much.)

Could some documentation be added, or the README links be updated?

**Comment by ForNeVeR** [comment]
Ah, I found the problem: the `markdownlint`'s master branch was renamed to `main`, that's why links are outdated. I'll file a pull request to update the links in this repository.

**Comment by DavidAnson** [comment]
Yes, thank you!

**Comment by DavidAnson** [comment]
I’m really glad you pointed this out! I’ve added master back to the repo for scenarios like this, though it is still not the default branch.

**Comment by ForNeVeR** [comment]
Thanks! I believe this is a good solution.
