### ISSUE TITLE
Consider adding homebrew installation option

### ISSUE THREAD

**Issue by pdesjardins90** [igorshubovych/markdownlint-cli#111]
When developing a project that has no package.json (for example, a shell script project), it would be nice to be able to include `markdownlint` in the project's brew bundle file instead of having to create a package.json just for it. This is something [Prettier](https://github.com/prettier/prettier), a project similar to yours, is doing. See [here](https://github.com/Homebrew/homebrew-core/blob/e9e4aa606c048454ef19ce16c2e71652984c9e73/Formula/prettier.rb).

Apart from writing the initial fomula (probably very similar to the one I linked), you'd have to include a way to update the hashes when you release a new version. I don't know what are the best practices for automating that, but my guess would be to do it through a github action.

Would you be open to add this feature to the project? If so, would you accept pull requests for it?

**Comment by DavidAnson** [comment]
The change you link to above is in the Homebrew repository - wouldn't the change you propose live there as well?

**Comment by pdesjardins90** [comment]
Yes it would, but from my understanding, developers are supposed to open pull requests to this package index with their package definitions (formula as they call it). It then acts as a kind of pointer to your latest released version

**Comment by DavidAnson** [comment]
I have no objections to the idea or PR's against the Homebrew repository, but would like to understand what the changes to this project would be.

**Comment by pdesjardins90** [comment]
The change to this project would only concern your release process

Once you've tagged a new version, the formula in Homebrew's repository should be updated with the new URL pointing to your release and its corresponding hash (for checksums). To do this, you'll have to open a pull request to their repository with this 2 lines change to your formula everytime. You'll either have to do it manually, or find a way to automate it

The initial formula is a single ruby script bearing your package name, dependencies and installation procedure, it will only have to be written once, unless you change the way your app is installed or its dependencies

I propose to write this initial formula myself and have you review it, I'll link it back to this issue when the PR exists

**Comment by nschonni** [comment]
I see there are a chunk of NPM packages already in Homebrew https://github.com/Homebrew/homebrew-core/search?q=npmjs&type=code but I'm not seeing why an NPM package would be installed through Homebrew rather than just `npm i -g markdownlint-cli`

**Comment by waldyrious** [comment]
@nschonni this is a CLI tool; it is implemented on top of Node.js, but it should work as a neutral executable, regardless of whether the end user has a Node.js development environment set up. Homebrew allows such tools to be installed and executed even on machines with no Node.js installed, by providing a brewed Node.js as a dependency.

**Comment by waldyrious** [comment]
> The change to this project would only concern your release process
>
> Once you've tagged a new version, the formula in Homebrew's repository should be updated

Just to clarify, the release process does not necessarily _have_ to change; for many Homebrew formulas, the version bump PRs are submitted by community members, not by the maintainers of the tools themselves. Of course, if they want to, they're welcome to do so (even better if that process is automated!), but making a tool available on Homebrew as a formula does not in itself require the maintainer to take on additional work in the release process.

**Comment by nschonni** [comment]
It appears the recipe is just installing it through NPM for the recipe https://github.com/Homebrew/homebrew-core/blob/e9e4aa606c048454ef19ce16c2e71652984c9e73/Formula/prettier.rb#L25

> work as a neutral executable

It still requires the Node runtime to execute, so I'm not sure that's true.

I'm not trying to block this, I'm just not seeing the benefit for installing NPM packages through Homebrew

**Comment by pdesjardins90** [comment]
My use case is to include a `Brewfile` with my repository so that a contributor can just run `brew bundle` and that would ensure all the required OS dependencies are available on his machine. Any dependency updates would be handled by `brew update` instead of relying on a mix of npm, yarn, pip, swift, etc.

In a pure javascript world, of course npm makes more sense, but since this is a markdown CLI tool, it's pretty universal and not specific to javascript development. I'm myself doing a shell script project and am documenting everything with markdown, for example.

**Comment by waldyrious** [comment]
> It appears the recipe is just installing it through NPM for the recipe

Yes, that's what I meant by "by providing a brewed Node.js as a dependency". Sorry that I didn't make that clear.

The benefit of Homebrew is that, in case someone doesn't have Node installed, they can just do `brew install markdownlint-cli` and Node+NPM will be installed for them, as indicated by the [depends_on "node"](https://github.com/Homebrew/homebrew-core/blob/e9e4aa606c048454ef19ce16c2e71652984c9e73/Formula/prettier.rb#L22) directive (or simply reused, if some other Node-based Homebrew formula has already installed it), and then NPM is used to install the module globally. So a single command gets the target tool available regardless of the user's existing setup.

Contrast with the alternative, which is to require the user to instal Node.js manually and then install the tool via NPM. Of course this is unnecessarily contrived if NPM is already present, but Homebrew provides a simple and stable solution that just works out of the box (and avoid any issues with e.g. Node version managers, etc.).
