### ISSUE TITLE
Feature: Support reading configuration from pyproject.toml

### ISSUE THREAD

**Issue by lyz-code** [igorshubovych/markdownlint-cli#113]
Hi. It seems that Python is slowly migrating to store all project configuration into the `pyproject.toml` file ([PEP 518](https://www.python.org/dev/peps/pep-0518/)). 

Can markdownlint-cli support this configuration method? Specifically, it would be nice if markdownlint-cli could understand `[tool.markdownlint]` section in the `pyproject.toml` file.

Not being Python based I can understand that you don't want to invest the effort.

**Comment by adam-grant-hendry** [comment]
+1 Please support!

**Comment by odimko** [comment]
Hi @DavidAnson ! Are there any updates on this? To be able to store `markdownlint-cli`'s configuration in `pyproject.toml` file, like other tools `ruff`, `pytest`, etc do?

**Comment by DavidAnson** [comment]
There are two parts to achieving this. The first is done by the issue linked above. The second is described by me here: https://github.com/igorshubovych/markdownlint-cli/pull/457#issuecomment-1945283551

**Comment by ModeSevenIndustrialSolutions** [comment]
+1 Adding my voice to those requesting support for configuration from pyproject.toml
