### ISSUE TITLE
Update to use markdownlint 0.3.1, enable resultVersion=1 for better output messages

### ISSUE THREAD

**Issue by DavidAnson** [igorshubovych/markdownlint-cli#12]

**Comment by pascalberger** [comment]
Current version seems to be updated to markdownlint 0.4.1, but support for resultVersion is still missing and would be a useful addition.

**Comment by DavidAnson** [comment]
Fixed by https://github.com/igorshubovych/markdownlint-cli/commit/c82a82efbdfa74a27ddbcc3983b3eb7debc6f935
