### ISSUE TITLE
Update to use markdownlint 0.4.1

### ISSUE THREAD

**Issue by DavidAnson** [igorshubovych/markdownlint-cli#13]
> 0.4.0 - Add MD044, enhance MD013/MD032/MD041/MD042/MD043, fix for MD038, dependencies.

**Comment by DavidAnson** [comment]
> 0.4.1 - Fixes for MD038/front matter, improvements to MD044, update dependencies.

**Comment by nikolay** [comment]
@igorshubovych Can you please upgrade the version?

**Comment by igorshubovych** [comment]
Fixed
