### ISSUE TITLE
Release of 0.25.0 to NPM

### ISSUE THREAD

**Issue by talpert** [igorshubovych/markdownlint-cli#131]
Hey there, I see you released a new version last week, but it doesn't appear to be available in NPM yet https://www.npmjs.com/package/markdownlint-cli. Would it be possible to push that up?
Thank you!

**Comment by DavidAnson** [comment]
Yes, sorry! I don't use the Releases tab in my own projects and probably got distracted updating that.

**Comment by DavidAnson** [comment]
Check now. :)

**Comment by talpert** [comment]
Thank you!
