### ISSUE TITLE
markdownlint reports npm ERR when run as npm script

### ISSUE THREAD

**Issue by lheberlie** [igorshubovych/markdownlint-cli#14]
Using the `npm script` reference: `npm run mdlint`

```
"scripts": {
  "mdlint": "node_modules/.bin/markdownlint --config .markdownlintrc source"
}
```

reports the following error:

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "mdlint"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! my-project@4.4.0 mdlint: `markdownlint --config .markdownlintrc source`
npm ERR! Exit status 1
```

However, if I issue the same command in the shell, it throws no errors:

`node node_modules/.bin/markdownlint --config .markdownlintrc source`

I had previously forked to [fix this issue](https://github.com/lheberlie/markdownlint-cli/blob/master/markdownlint.js#L66), but if you could fix it in your repo then I would have a need for the fork.

Thank you for contributing this utility.

**Comment by Akurganow** [comment]
Has the same error but when try to use glob
I try both of `yarn` and `npm` like `yarn run mdlint`
```json
"scripts": {
  "mdlint": "markdownlint ./!(node_modules)/*"
},
```

Reports this error
```bash
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `markdownlint !(node_modules)/* '
error Command failed with exit code 2.
```

If try to run command `markdownlint ./!(node_modules)/*` right in the shell, it throw no errors

**Comment by davidosomething** [comment]
@lheberlie how about `"mdlint": "markdownlint -- --config .markdownlintrc source"`
@Akurganow the glob is a bashism, the npm shell is `sh`.

**Comment by DavidAnson** [comment]
The relevant code has changed a bit since this issue was opened. Could you please take another look in light of the suggestions immediately above and say if this is still a problem? Thanks!

**Comment by lheberlie** [comment]
@DavidAnson - thanks for the followup.

If you run a script using the `npm run foo` workflow against the `markdownlint-cli` module and there are Markdown syntax errors, the [`printResult`](https://github.com/igorshubovych/markdownlint-cli/blob/master/markdownlint.js#L73) function sets the [`process.exitCode=1`](https://github.com/igorshubovych/markdownlint-cli/blob/master/markdownlint.js#L73) which causes the npm script to report that the node process has exited with errors. While there are errors in the markdown, there aren't any errors in the `markdownlint-cli` module. I think this gives the user the idea that the script failed. Changing the [`process.exitCode=0`](https://github.com/igorshubovych/markdownlint-cli/blob/master/markdownlint.js#L73) allows the `npm run foo` script to execute successfully, while still reporting the errors.

I am able to execute `npm run mdlint`, but if there are errors in the markdown then the script fails due to the node process setting its `exitCode = 1`.

`"mdlint": "node_modules/.bin/markdownlint --config .markdownlintrc source"`

```shell
npm run mdlint

> test@4.7.0 mdlint /Users/local/myproject
> markdownlint --config .markdownlintrc source

heb:test local(master)$ npm run mdlint

> test@4.7.0 mdlint /Users/local/myproject
> markdownlint --config .markdownlintrc source

source/sample-code/sample/description.md: 77: MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "  ```"]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@4.7.0 mdlint: `markdownlint --config .markdownlintrc source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@4.7.0 mdlint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/local/.npm/_logs/2018-01-02T22_33_05_039Z-debug.log
```

What do you think?

**Comment by DavidAnson** [comment]
I think the use of exit code for more than just program failure to run is normal and makes it easy to detect errors in an automated way.

For example, the mocha runner sets the exit code to the number of test cases that failed: https://github.com/mochajs/mocha/blob/master/bin/_mocha

ESLint behaves similarly: https://github.com/eslint/eslint/blob/master/lib/cli.js

If I’m understanding the issue correctly, I believe the current behavior is by design.

**Comment by lheberlie** [comment]
@DavidAnson - thanks for the feedback, I'll close the issue.

**Comment by Stanzilla** [comment]
So what's the suggested way to use markdownlint from a node script then?

**Comment by DavidAnson** [comment]
I have a list of example projects using markdownlint and either as a package or via the CLI here: https://github.com/DavidAnson/markdownlint/blob/master/README.md#examples
