### ISSUE TITLE
Correct use of the -i option?

### ISSUE THREAD

**Issue by michaelbowler** [igorshubovych/markdownlint-cli#154]
I'm trying to exclude a directory from the markdownlint checker. 

I try:
 `markdownlint **/*.md -i  /docs/Migrated_Content/*.md`
and variations like
 `markdownlint **/*.md -i  /docs/Migrated_Content/`
 `markdownlint **/*.md -i  /Migrated_Content`
 
 Etc, but the linter always looks into "Migrated_Content"
 
 
 What am I doing wrong?
 
 Thanks in adv

**Comment by DavidAnson** [comment]
The leading `/` in the path means it is absolute, starting from the root of your drive. You probably want `./docs/blah` instead to identify a subdirectory of the current directory.

**Comment by michaelbowler** [comment]
Thanks for clarification.
