### ISSUE TITLE
specify required `language_version: ...` in .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by dev-zero** [igorshubovych/markdownlint-cli#157]
One of the recent changes causes `markdownlint` to fail with node < 10, see cp2k/cp2k#1296.
Unfortunately node-8 seems to be still pretty common as a pre-installed node version on openSUSE (LEAP) systems. Specifying a recent enough version with `language_version: ...` in this hooks config would remedy the problem, with the drawback though that everyone will get an additional node installation, even if they already have one which would be suitable.

**Comment by DavidAnson** [comment]
Node 8 went end-of-life at the end of 2019. This project dropped support almost a year ago: https://github.com/igorshubovych/markdownlint-cli/commit/a1713b78750835362f5f686684db2973eaa39ff1

**Comment by dev-zero** [comment]
Yes, I know. But for example Ubuntu 18.04 also still has 8.10:
https://packages.ubuntu.com/bionic/nodejs

**Comment by DavidAnson** [comment]
Any dependency of this project could reasonably introduce a break for any unsupported version of Node at any time. Do you have a suggestion for how to handle that? In my mind, the only reliable strategy is for the ecosystem to focus on supported versions of Node only.

**Comment by dev-zero** [comment]
I am not sure I fully understand it, but using `language_version: ...` to specify a specific version is being passed on directly to `nodeenv` with the `-n ...` flag, triggering an installation of the specific node version in an isolated environment for this hook (instead of using the system-version). And since this package has a `package-lock.json` users of this hook should get the very same versions of the node packages as this package was tested with, correct? So there should be no side-effects and also no accidental breakages if a dependency gets updated?

**Comment by DavidAnson** [comment]
If you're okay using old versions of the package and its dependencies, you can install the version of this CLI from a year ago before the depreciation. But the markdownlint library (for example) also supports Node >= 10 and that could impact users of the CLI on Node 8 at any time. The option would be to stop updating CLI dependencies, but then you may as well use an older version.

**Comment by dev-zero** [comment]
@DavidAnson I still don't understand it, I am afraid. I am not asking for `markdownlint-cli` to support node < 10, but only to consider to specify a `language_version: ...` with a suitable version of node instead of relying on the system-version being recent enough (if a system-version is detected by `pre-commit`).
This would enforce a specific (compatible) node-version to be used for `markdownlint-cli`.

Another option would be to simply inform the user properly about a too old node version (maybe by using [check-node-version](https://www.npmjs.com/package/check-node-version#check-node-version-api-usage)) instead of failing due to a syntax error.

**Comment by DavidAnson** [comment]
Sorry, I completely misunderstood. Your proposal makes sense and I'll do it for the next release. Thanks for clarifying!

**Comment by DavidAnson** [comment]
As far as I can tell, `language_version` must be a specific version number (which I don’t want to update every time Node is patched) or maybe “latest”.

- https://github.com/search?q=node+language_version+filename%3A.%2Fpre-commit-hooks.yaml&type=code
- https://pre-commit.com/#overriding-language-version
- https://github.com/ekalinin/nodeenv#advanced
- https://github.com/ekalinin/nodeenv/search?q=latest

Do you know one way or another, @dev-zero? Are you able to point your configuration to a branch of this repo?

**Comment by DavidAnson** [comment]
Try setting `rev` in your `.pre-commit-config.yaml` to `language_version` or this commit hash to test using `latest`: https://github.com/igorshubovych/markdownlint-cli/commit/4b980c162f7d0e45e812af6e5853b99a10646b5b

**Comment by dev-zero** [comment]
> Do you know one way or another, @dev-zero?

Unfortunately not, no.
There are the following issues in `nodeenv` which would allow you to specify a minimal required version and re-use a system-node satisfying that version constraint, once implemented:
* https://github.com/ekalinin/nodeenv/issues/152
* https://github.com/ekalinin/nodeenv/issues/153

> Are you able to point your configuration to a branch of this repo?

Yes, will try.

This means that every time `pre-commit` updates the environment (for example because the `markdownlint-cli` was updated) it will pull the latest `node`. I guess everyone can live with that?

**Comment by DavidAnson** [comment]
Agreed. My change in the `language_version` branch is not ideal because it will do extra work, but should always work and therefore seems better than how things are today. Getting the fixes you link to would improve this. Please let me know how your experiment goes!

**Comment by asottile** [comment]
Please don't set `language_version: latest` in hooks files -- this breaks the framework defaults.  This should be overridden in a problematic individual's `.pre-commit-config.yaml` only if needed

**Comment by DavidAnson** [comment]
@asottile Can you please explain what this breaks? Per this issue, not setting a version leads to undefined behavior that can fail. Setting a minimum version is not supported. So setting `latest` seems the next best thing. It may cause an extra install, but that should not affect other things?

**Comment by asottile** [comment]
it causes, for example, disk usage to be 99% larger than necessary -- it also breaks `node` usage on M1 and alpine.  users with non-modern node are by far the minority

**Comment by DavidAnson** [comment]
Extra disk use is annoying, but better than undefined/failing behavior. What breaks on M1/Alpine? Does this CLI does not work on Node 15 on those platforms?

I left this issue open a month and nobody had any better ideas. :(

**Comment by asottile** [comment]
currently non-prebuilt platforms (especially non-glibc) aren't really functional via nodeenv so `system` (the default when `node` is available) is the only reasonable way to get those running

leaving out `language_version` doesn't preclude a user from adding it to their own repository -- that's kind of the point of pre-commit's cascading configuration.  the base repository should set reasonable defaults

**Comment by DavidAnson** [comment]
If I understand correctly, leaving out a language version implies that a tool works with any language version and that claim is wrong for this tool. Running on older versions of node is known to be broken and actual users have hit that problem. Therefore, specifying a version of some kind seems necessary. Ideally, I would specify the range of versions that are currently tested/supported, but that does not seem to be possible. Which leaves the option of specifying a particular version or "latest" as is done here. Specifying a particular version is nice because it won't change one day when a new version of node is released, but it seems worse for every tool in the ecosystem to specify a particular version because the chances they all agree are low and many different versions of node will need to be installed to satisfy the various tools a project may reference. Instead, using the "latest" version for all tools that support it seems most likely to lead to sharing and efficiency. This seems to me to be the least wrong thing I can do as a tool author. If there is another approach that I should consider, please let me know! However, I would rather not go back to excluding version because that is known to cause problems for actual users.

**Comment by asottile** [comment]
I'm asking you to please remove `language_version` and document for those running on unsupported platforms to include `language_version: latest` in their configuration instead of burdening all other users with the side-effects of your choices here

**Comment by DavidAnson** [comment]
Is there no way for a tool to behave reasonably here? I’ve looked back at the docs (https://pre-commit.com/#pre-commit-configyaml---hooks) and the current use seems appropriate. That said, I can remove it if it’s wrong, but what part of the precommit docs should I link to I that explains this in detail for users who get broken?

**Comment by asottile** [comment]
this is probably the most appropriate place to link: https://pre-commit.com/#config-language_version

**Comment by asottile** [comment]
ideally some effort would be put into `nodeenv` to support `>=` specifiers for versions, though I don't know of anyone working on that at the moment

**Comment by DavidAnson** [comment]
Updated - thanks for the feedback.

**Comment by mschoettle** [comment]
@asottile Has the stance on specifying `language_version` in `.pre-commit-hooks.yaml` changed since 2021? Would it be appropriate to specify `language_version: lts` (which was introduced after the discussion above)?

Since node 23 was released one of our hooks fails in CI or locally after running `pre-commit clean`. See the error log here: https://github.com/DavidAnson/markdownlint-cli2/issues/437
