### ISSUE TITLE
[docs] config file options

### ISSUE THREAD

**Issue by naseemkullah** [igorshubovych/markdownlint-cli#158]
Hello! 

Would it be possible for the REAMDE to provide an up to date list of all possible configuration options for the config file?

**Comment by DavidAnson** [comment]
This section of the docs has multiple links: https://github.com/igorshubovych/markdownlint-cli#configuration

Including a list of rules: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

And an explanation of the format: https://github.com/DavidAnson/markdownlint#optionsconfig

What else are you thinking should be included?

**Comment by DavidAnson** [comment]
Are you looking for something like `.markdownlint.yaml` from your PR? (Except exhaustive.)

**Comment by jsumners** [comment]
> Are you looking for something like `.markdownlint.yaml` from your PR? (Except exhaustive.)

Yes. Having to piece together all of the parts is difficult for someone without much time.

**Comment by DavidAnson** [comment]
Okay, I should be able to add something to make this more explicit.

FYI, if you edit the configuration file in VS Code with the `markdownlint` extension installed, you'll get full intellisense.

Also FYI, if you use CLI2, I already have something like this for it's higher-level configuration file:
- https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml
- https://github.com/DavidAnson/markdownlint-cli2/blob/main/test/markdownlint-cli2-jsonc-example/.markdownlint-cli2.jsonc

**Comment by DavidAnson** [comment]
FYI @naseemkullah / @jsumners, this is on the way: https://github.com/DavidAnson/markdownlint/commit/5b7e9b87be062d9e6224ccfcbc54182ff1120ce9

**Comment by jsumners** [comment]
Looks fantastic. Thank you for accepting the feedback.
