### ISSUE TITLE
Unexpected "command not found" error after markdownlint-cli installation

### ISSUE THREAD

**Issue by alvinseville7cf** [igorshubovych/markdownlint-cli#182]
Hello! I've installed markdownlint-cli via `choco install markdownlint-cli -y` but when I ran `markdownlint --help` I obtained `bash: markdownlint: command not found` error. Is it normal behavior?

**Comment by DavidAnson** [comment]
I think choco is a Windows installer and bash is a Linux shell, so something seems a little off. Please check where the install happened, confirm that is in the path for bash, whether you can run it directly, whether it works from Windows command prompt, etc., and reply with the results.
