### ISSUE TITLE
Release new version containing `--json`

### ISSUE THREAD

**Issue by fnando** [igorshubovych/markdownlint-cli#199]
Hi there!

`--json` support was introduced in https://github.com/igorshubovych/markdownlint-cli/pull/195, but a new version of the package was never published to NPM.

It'd be great if you could make a new release with this feature.

**Comment by DavidAnson** [comment]
Will do - probably mid-July.

**Comment by DavidAnson** [comment]
Done: https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.28.0
