### ISSUE TITLE
Support cross-platform glob

### ISSUE THREAD

**Issue by yassh** [igorshubovych/markdownlint-cli#20]
It would be nice to support cross-platform glob like [prettier](https://github.com/prettier/prettier#cli).

Currently markdownlint-cli supports directory.
But if directory has node_modules directory, markdownlint-cli also search in it.
To avoid that, I want to use glob like this:

```
# ./ has node_modules directory and *.md file exists in ./ and ./docs
markdownlint './*.md' './docs/**/*.md'
```

**Comment by unindented** [comment]
Hey @igorshubovych, is the project abandoned?
