### ISSUE TITLE
Publish "official" container image for markdownlint-cli

### ISSUE THREAD

**Issue by tylerauerbeck** [igorshubovych/markdownlint-cli#205]
Would there be any interest in publishing an "offical" docker image for markdownlint-cli? Right now I see a number of entries on dockerhub in personal repositories or the other option of building it yourself. It would be great to just rely on an already published image that has a higher level of trust (direct from the source!).

If there is interest, I have workflows from other projects that could just be tied into github actions and images could be published on merge (`latest`) and when a release is cut (`vX.Y.Z`). This could also all just be done directly in GitHub by publishing the image to the GH Container Registry if the overhead of a repo in docker or quay is too much.

Just wanted to gauge interest before opening a PR.

**Comment by pellared** [comment]
Personally I use https://gitlab.com/06kellyjac/docker_markdownlint-cli

**Comment by 06kellyjac** [comment]
> @06kellyjac, what do you think about spending that time instead to help complete the work here to automatically push container images to the GitHub store upon release? If successful, it should save you time as well. :)

You mean help with #208 ?
Yeah, can do

**Comment by DavidAnson** [comment]
Done: https://github.com/igorshubovych/markdownlint-cli/pull/208#issuecomment-1033361145

**Comment by 06kellyjac** [comment]
:tada: very nice.

Sorry I wasn't very helpful but I'll give it a review and archive my repos :)
