### ISSUE TITLE
`--cache` option

### ISSUE THREAD

**Issue by Yash-Singh1** [igorshubovych/markdownlint-cli#209]
There could be a `--cache` option that creates a `.markdownlintcache` file with the write time stamps of each file and their respective errors. This could boost performance on minor changes significantly.

**Comment by DavidAnson** [comment]
There haven't been many performance complaints - and none currently open - so I'm not planning changes here. If speed is an issue for very large repositories, there are already tools to help with scanning just changed files. Here is one example using GitHub Actions: https://github.com/DavidAnson/markdownlint-cli2-action/blob/main/.github/workflows/changed.yml
