### ISSUE TITLE
Should exit non-zero on bad args

### ISSUE THREAD

**Issue by janosh** [igorshubovych/markdownlint-cli#236]
Right now, when calling `markdownlint` with bad arguments, it gives you the CLI docs but exits with 0 which is bad for tools like pre-commit which think everything was fine when in fact `markdownlint` didn't run at all.

```sh
$ markdownlint --fix

Usage: markdownlint [options] <files|directories|globs>

MarkdownLint Command Line Interface

Options:
  -V, --version                               output the version number
  -c, --config [configFile]                   configuration file (JSON, JSONC, JS, or YAML)
  -d, --dot                                   include files/folders with a dot (for example
                                              `.github`)
  -f, --fix                                   fix basic errors (does not work with STDIN)
  -i, --ignore [file|directory|glob]          file(s) to ignore/exclude (default: [])
  -j, --json                                  write issues in json format
  -o, --output [outputFile]                   write issues to file (no console)
  -p, --ignore-path [file]                    path to file with ignore pattern(s)
  -r, --rules  [file|directory|glob|package]  custom rule files (default: [])
  -s, --stdin                                 read from STDIN (does not work with files)
  -h, --help                                  display help for command

$ echo $?
0

**Comment by DavidAnson** [comment]
I think #104 shows an even more problematic scenario for the same issue.

**Comment by janosh** [comment]
So what integer would you like to exit on bad args? Looks like [1](https://github.com/igorshubovych/markdownlint-cli/blob/bf8b1484934b89c791b9aab83c2c6cc950546be4/markdownlint.js#L74), [2](https://github.com/igorshubovych/markdownlint-cli/blob/bf8b1484934b89c791b9aab83c2c6cc950546be4/markdownlint.js#L189) and [3](https://github.com/igorshubovych/markdownlint-cli/blob/bf8b1484934b89c791b9aab83c2c6cc950546be4/markdownlint.js#L257) are already used for linting results, unable to write to output file and unable to load custom rule file, respectively. Shall we go with `exit(4)` for bad args?

**Comment by DavidAnson** [comment]
That seems reasonable! However I'd like to be really clear here that the problem is "no files found to lint" rather than "bad argument". This is more clear in the other issue I linked where the person had passed a glob and it just didn't happen to include anything. Not passing a glob at all (this issue) is an extreme version of that problem. :)
