### ISSUE TITLE
Inessential dependencies

### ISSUE THREAD

**Issue by janosh** [igorshubovych/markdownlint-cli#237]
@igorshubovych What's your take on getting rid of superseded dependencies? There are a few things here like `lodash.flatten` that could be replaced with standard library alternatives, in this case [`arr.flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility) available since `node` v11. Would help with bringing install times and disk usage down.

**Comment by DavidAnson** [comment]
Happy to see this and love the idea as I am a dependency minimalist myself. The minimum supported Node version now is 12 (this should be reflected in package.json?) and my favorite site to check is https://node.green/.
