### ISSUE TITLE
markdownlint as a peer dependency?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [igorshubovych/markdownlint-cli#25]
Keeping `markdownlint` itself as a direct `dependency` in `package.json` somewhat locks this package into that version. If you mark it as a `devDependency`, users will have an easier time managing versioning. 

The setup flow would become:

```shell
npm i -g markdownlint markdownlint-cli
```

**Comment by DavidAnson** [comment]
After reading the documentation for `peerDependencies`, this scenario does *not* seem to match the “plugin” model that is meant for: https://nodejs.org/en/blog/npm/peer-dependencies/

Rather, it seems like the common “simple CLI supports the latest features of specific library” scenario which is commonly implemented as a `dependency` in places like: https://github.com/sindresorhus/cpy-cli

 Unless I am misunderstanding something, I am inclined to close this issue.
