### ISSUE TITLE
New release with markdownlint >= 0.25.0 ?

### ISSUE THREAD

**Issue by TheCleric** [igorshubovych/markdownlint-cli#257]
This looks updated in master, but it would be cool to get a new release with this dependency bump in as it would clear out some npm audit warnings.

**Comment by DavidAnson** [comment]
Yes, that's my current focus.

**Comment by TheCleric** [comment]
> Yes, that's my current focus.

Thanks for your hard work!

**Comment by Siemienik** [comment]
Thank you @TheCleric! I keep finger crossed :)

**Comment by Siemienik** [comment]
@DavidAnson, is any way how could I help you achieve this issue?

**Comment by DavidAnson** [comment]
Thank you, but no. I want to finish looking at the Prettier PR, then should be ready to publish the release.

**Comment by DavidAnson** [comment]
https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.31.0

**Comment by Siemienik** [comment]
Thank you, I've just updated my dependencies and alls is vulnerable-free 🥇
