### ISSUE TITLE
[fail] "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by ybiquitous** [igorshubovych/markdownlint-cli#27]
Because the executable script in `markdownlint-cli@0.4.0` contains CRLF, the command fails.

```sh
$ ./node_modules/.bin/markdownlint *.md
env: node\r: No such file or directory

$ file ./node_modules/.bin/markdownlint
./node_modules/.bin/markdownlint: a /usr/bin/env node script text executable, ASCII text, with CRLF line terminators
```

### Environments

- Node 8.9.1
- Yarn 0.27.5

### Links

- https://github.com/ybiquitous/ybiq/pull/46
- https://travis-ci.org/ybiquitous/ybiq/jobs/299474891

**Comment by DavidAnson** [comment]
Very sorry! Please try upgrading to `0.4.1`. Thank you!

**Comment by ybiquitous** [comment]
@DavidAnson Thanks a lot! 👍
