### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by jurijzahn8019** [igorshubovych/markdownlint-cli#296]
Hi there,

i am sorry to bother you, but last release was a while go, and i desperately wating for: https://github.com/igorshubovych/markdownlint-cli/issues/269

When can we expect this?

Thanks :smile:

**Comment by DavidAnson** [comment]
I released a new version of the library just last night: https://github.com/DavidAnson/markdownlint

I will now do the rounds of updating things that use it - like this project.

I typically update this project last because it has the biggest reach and I want to find/fix any glaring issues first.
