### ISSUE TITLE
Release support for markdownlint v0.26.0

### ISSUE THREAD

**Issue by edemaine** [igorshubovych/markdownlint-cli#299]
Can the dependencies be updated to markdownlint v0.26.0 which includes useful new rules?

Alternatively, perhaps markdownlint should be a peer dependency so that the user can choose their version? Up to you.

Happy to make a PR if that would help.

**Comment by DavidAnson** [comment]
Already done for the next release: https://github.com/igorshubovych/markdownlint-cli/commit/dcbd7bc3e073317a376203df2078a38341ff278e

**Comment by edemaine** [comment]
Oops, sorry. I guess you can reinterpret to "can haz release plz?" 😅

(Context: I wanted to test/migrate to the new link-fragments rule so I can deprecate my https://github.com/edemaine/markdownlint-rule-github-internal-links)

**Comment by DavidAnson** [comment]
Yes, I'm in a release cycle now. I update this package last because it has the biggest scope and I want to catch any issues when they are small. I hope to have a new CLI2 out soon which may help you?

**Comment by TheJaredWilcurt** [comment]
I'd also like `markdownlint-cli` to do a new release with the latest `markdownlint` version.

**Comment by DavidAnson** [comment]
Version `0.32.0` is published: https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.32.0
