### ISSUE TITLE
Unable to pipe output

### ISSUE THREAD

**Issue by txtsd** [igorshubovych/markdownlint-cli#304]
I'm trying to `grep` for specific rules in the output, but it does not work.

I want to be able to run `markdownlint . | grep MD025` for example.

**Comment by DavidAnson** [comment]
Errors are written to `stderr`, not `stdout`. Your shell probably has a way to change what is piped.

**Comment by txtsd** [comment]
Thanks! I found it.

POSIX compliant:

```bash
markdownlint . 2>&1 | grep MD025
```

ZSH specific:

```zsh
markdownlint . |& grep MD025
```
