### ISSUE TITLE
Support arm64 Container Image

### ISSUE THREAD

**Issue by mvrahden** [igorshubovych/markdownlint-cli#322]
Hello can you please add support `arm64` platform container Images?

**Comment by DavidAnson** [comment]
FYI, CLI2 has this already: https://github.com/DavidAnson/markdownlint-cli2

**Comment by mvrahden** [comment]
@DavidAnson thanks for the quick response :) I'll definitely have a look at it!

**Comment by stmcginnis** [comment]
This was closed by pointing to a different project's image. Are you saying this project should no longer be used and users should migrate to CLI2? Otherwise I think this should be reopened.

**Comment by DavidAnson** [comment]
This issue was closed with a commit to this repository which I made to fix the issue for this project: https://github.com/igorshubovych/markdownlint-cli/commit/85f4052eb517703d4a657d7c8ac0ed7f1f375760

**Comment by stmcginnis** [comment]
Ah, sorry! I completely missed the commit reference. I must have been looking for a linked PR. Thanks @DavidAnson!
