### ISSUE TITLE
MD013 rule not respected

### ISSUE THREAD

**Issue by waldronmatt** [igorshubovych/markdownlint-cli#325]
MD013 rule is not respected in `.markdownlint.json` . When linting files using `markdownlint --fix **/*.md` or `markdownlint **/*.md`, line length errors output. Changing the line length to a number other than 80 also does not work. I'm using version `0.32.2`.

The solution involved disabling the ruleset manually via cli command: `--disable MD013`.

```json
{
"MD013": false,
}
```

```json
{
"line-length": false,
}
```

Error output:
```bash
$ markdownlint --fix **/*.md --ignore node_modules --ignore **/CHANGELOG.md
docs/GETTINGSTARTED.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 107]
docs/PUBLISHING.md:7:81 MD013/line-length Line length [Expected: 80; Actual: 191]
docs/PUBLISHING.md:9:81 MD013/line-length Line length [Expected: 80; Actual: 114]
docs/PUBLISHING.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 132]
packages/browserslist-config/README.md:15 MD040/fenced-code-language Fenced code blocks should have a language specified [Context: "```"]
packages/eslint-config/README.md:59:81 MD013/line-length Line length [Expected: 80; Actual: 92]
packages/lint-staged-config/README.md:35:81 MD013/line-length Line length [Expected: 80; Actual: 108]
packages/semantic-release-config/README.md:77:81 MD013/line-length Line length [Expected: 80; Actual: 114]
packages/webpack-config/README.md:3:81 MD013/line-length Line length [Expected: 80; Actual: 91]
README.md:3:81 MD013/line-length Line length [Expected: 80; Actual: 99]
README.md:5:81 MD013/line-length Line length [Expected: 80; Actual: 176]
README.md:15:81 MD013/line-length Line length [Expected: 80; Actual: 95]
README.md:20:81 MD013/line-length Line length [Expected: 80; Actual: 438]
README.md:26:81 MD013/line-length Line length [Expected: 80; Actual: 238]
README.md:34:81 MD013/line-length Line length [Expected: 80; Actual: 213]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DavidAnson** [comment]
JSON does not allow the trailing comma shown in both of your examples. Please try removing it.

**Comment by waldronmatt** [comment]
Poor example I wrote. The full example I'm using looks like this:

```json
{
  "default": true,
  "MD004": { "style": "dash" },
  "MD007": { "indent": 2 },
  "MD026": false,
  "MD029": { "style": "ordered" },
  "MD033": false,
  "MD034": false,
  "MD036": false,
  "MD041": false,
  "line-length": false,
  "no-hard-tabs": false,
  "whitespace": false
}

```

**Comment by DavidAnson** [comment]
If the other configurations are working correctly, please check those files for in-line comments that may be overriding your preferences. Or share a link to the repository and I can have a look directly.

**Comment by waldronmatt** [comment]
Other configurations seemed to be working correctly and couldn't find anything that would be interfering with my configurations. Here's a link to the repo https://github.com/waldronmatt/shareable-configs

**Comment by DavidAnson** [comment]
I won't be able to try anything on a computer till tomorrow or so, but one odd thing is that you have a dependency on the library from package.json, but your lint script runs the CLI. You may want to change that dependency to be on markdownlint-cli instead. I'm not sure where it's pulling from now, perhaps global?

**Comment by waldronmatt** [comment]
In my monorepo's markdownlint, I was trying to extend from my reusable configuration.

Original .`markdownlintrc.json`
```json
{
  "extends": "./packages/markdownlint-config"
}
```

This configuration fixes the MD013 issue:

New .`markdownlintrc.json`
```json
{
  "extends": "./packages/markdownlint-config/index.json"
}
```

@DavidAnson do you have any recommendations/guidelines for using/referencing a reusable markdownlint configuration?

**Comment by DavidAnson** [comment]
"extends" takes a path to a file, not a package.

**Comment by waldronmatt** [comment]
makes sense, thanks for you help on this. Will extend to the file itself.
