### ISSUE TITLE
MD037 identifies underscores within a word as the beginning of emphasized text

### ISSUE THREAD

**Issue by ansiblehamster** [igorshubovych/markdownlint-cli#345]
When MD037 sees markdown such as:

<code>src\_host | \_string\_</code>

it interprets the <code>\_</code> in <code>src\_host </code> as the beginning of emphasis and the first underscore of <code>\_string\_</code> as the end, interpreting the emphasized text as:

<code><code>\_host | \_</code>

 Then it issues a warning about the space before the final underscore.

While the original markdown spec allows either <code>\*</code> or <code>\_</code> to begin emphasis inside of a word, many modern implementations (including Github's; see <https://github.github.com/gfm/#emphasis-and-strong-emphasis> and <https://github.github.com/gfm/#example-369>) do not allow <code>\_</code> to start emphasis within a word.  For example:

| markdown | rendered text |
| -------- | -------- |
| \*unopenable\* | *unopenable* |
| \_unopenable\_ | _unopenable_ |
| un\*open\*able | un*open*able |
| un\_open\_able | un_open_able |

The final case comes up frequently when documenting code which is why many markdown renderers ignore it.

**Comment by DavidAnson** [comment]
Your example does not produce a warning in the latest release of the library. Could you please double check you are in the latest CLI release?

https://dlaa.me/markdownlint/#%25m%23%20CLI%20345%0A%0Asrc_host%20%7C%20_string_%0A

**Comment by ansiblehamster** [comment]
Interesting.  I'm using the latest version of the Github super-linter.  Apparently the super-linter is not using the latest version of markdownlint-cli.

**Comment by nschonni** [comment]
It is https://github.com/github/super-linter/blob/37b6ff9a3fe5e104bb33af6d200d7c20d77b5e47/dependencies/package.json#LL31C15-L31C15

**Comment by ansiblehamster** [comment]
Maybe I'm launching it incorrectly:

<code>
$ sudo docker run -e RUN_LOCAL=true -e USE_FIND_ALGORITHM=true -v ./test/test.md:/tmp/lint/test.md github/super-linter
...
2022-12-20 20:28:52 [INFO]   Linting [MARKDOWN] files...
2022-12-20 20:28:52 [INFO]   ----------------------------------------------
2022-12-20 20:28:52 [INFO]   ----------------------------------------------
2022-12-20 20:28:52 [INFO]   ---------------------------
2022-12-20 20:28:52 [INFO]   File:[/tmp/lint/test.md]
2022-12-20 20:28:52 [ERROR]   Found errors in [markdownlint] linter!
2022-12-20 20:28:52 [ERROR]   Error code: 1. Command output:
------
/tmp/lint/test.md:3:4 MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "_host | _"]
------
</code>

**Comment by nschonni** [comment]
It's likely just something that is fixed in the library, but not released to CLI(s) yet.

**Comment by nschonni** [comment]
if you want to confirm it's not the superlinter, you can always run the plain cli `npx markdownlint /tmp/lint/test.md`

**Comment by ansiblehamster** [comment]
<code>
$ sudo docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest "test/test.md"
</code>

runs with no errors so something's up with the super-linter, I guess.  I'll just ignore MD037 for now and check on it later.

Thanks.
