### ISSUE TITLE
Allow markdownlint v0.27.0

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [igorshubovych/markdownlint-cli#347]
There's a new version of Markdownlint available 🎉: https://github.com/DavidAnson/markdownlint/issues/669 -> https://github.com/DavidAnson/markdownlint/commit/5a4cf179c42646a0ad48c3f9522fe324849d73ba. But the semver range on `markdownlint-cli` is `~0.26.2`, so 27 isn't allowed.

Could we increase that version range? I'd be happy to send a PR!

**Comment by DavidAnson** [comment]
0.26.2 to 0.27.0 is a semver-breaking change and should not happen automatically.

**Comment by DavidAnson** [comment]
Fixed by: https://github.com/igorshubovych/markdownlint-cli/commit/0b87e04784235aa82d9a07cd0b9a5056ff44cee0

**Comment by DavidAnson** [comment]
https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.33.0

**Comment by JoshuaKGoldberg** [comment]
Thanks! 🙌
