### ISSUE TITLE
markdownlint now analyzing stdin unnecessarily

### ISSUE THREAD

**Issue by stevemart** [igorshubovych/markdownlint-cli#35]
This may be a byproduct of #32 -- i just recently started to see it. I'm using markdownlint-cli@0.8.0 

We were passing in a list of directories, each containing a markdown file, to be analyzed while skipping over the node_modules directory. Just started to see an error related to stdin.  Not sure if we're abusing the file input argument, but would be great to see if this is related to the latest version of markdownlint-cli.

```
$ markdownlint --config .markdownlint.json `ls -d */ | grep -v 'node_modules/'`
stdin: 1: MD043/required-headers Required header structure [Context: "## Learning objectives"]
```

our markdownlint.json file looks like

```
{
    "_docs_for_this_file": "https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md",
    "line-length": false,
    "first-line-h1": false,
    "first-header-h1": {
        "level": 2
    },
    "header-style": {
        "style": "atx"
    },
    "ul-style": {
        "style": "asterisk"
    },
    "hr-style": {
        "style": "---"
    },
    "fenced-code-language": false,
    "required-headers": {
        "headers": [
            "## Learning objectives",
            "## Prerequisites",
            "## Estimated time",
            "## Steps",
            "*",
            "## Summary",
            "## References"
        ]
    },
    "spelling": false,
    "no-alt-text": false
}
```

**Comment by DavidAnson** [comment]
Yes, it looks like it thinks you have passed `—stdin` to use that for input. Can you share the result of that backtick command you are passing to identify files? Is there a chance that “stdin” appears in that list in some form and is confusing the command line parser?

**Comment by DavidAnson** [comment]
Addendum: `-s` in that list would have the same effect.

**Comment by DavidAnson** [comment]
Even better, is your repo public so I can experiment directly?

**Comment by DavidAnson** [comment]
Actually, can you put “—“ between the options and the list in the usual manner? That should prevent anything in the list from interfering.

See also:
- https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash
- https://github.com/tj/commander.js/blob/master/test/test.literal.args.js

**Comment by stevemart** [comment]
@DavidAnson thanks for getting back to me. Adding a `--` between the options doesn't seem to help. There are no directories with a `-stdin` in their name, but there are some with a `-s` like `-spark`. I moved those directories out but that didn't help either. The repo is in a GHE unfortunately, but I can share the output of the command in the backticks (https://pastebin.com/RimTqT29). Below is some of my tinkering.

Trying out the double dash:
```
smartinelli-mac howtos $ markdownlint --config .markdownlint.json -- `ls -d */ | grep -v 'node_modules/'`
stdin: 1: MD043/required-headers Required header structure [Context: "## Learning objectives"]
```

Removing any directories with a `-s` in the name
```
smartinelli-mac howtos $ mv *-s* ~
smartinelli-mac howtos $ markdownlint --config .markdownlint.json -- `ls -d */ | grep -v 'node_modules/'`
stdin: 1: MD043/required-headers Required header structure [Context: "## Learning objectives"]
```

Thanks in advance for your help!

**Comment by stevemart** [comment]
Though it's pretty obvious, for completion i'll state that rolling back to 0.7.1 made my travis job happy :)

**Comment by DavidAnson** [comment]
Good, at least you're not blocked!

I don't know what a GHE is, but would it be possible for you to create a simple repo or ZIP that demonstrates the problem? Nothing I've tried locally so far (on Windows) does.

Also, what version of Node.js are you using?

And are you okay trying a custom version of `markdownlint.js`? I could create a version with extra logging and you'd just need to overwrite it in your local install and run one of the commands above.

Sorry for the trouble - thanks for your help here!!

**Comment by DavidAnson** [comment]
Ah, I found a repro on Linux (well, technically, Linux Subsystem for Windows). I need to run now, but should be able to experiment with this locally.

**Comment by DavidAnson** [comment]
Embarrassingly, the repro works on Windows as well now that I know what's going on. Entirely my fault, it should be easy to fix. Sorry for the runaround above!

**Comment by stevemart** [comment]
> I don't know what a GHE is

Oops, Github Enterprise, behind our firewall and all that. 

> It should be easy to fix

Yay! 

Thanks for your help!

**Comment by DavidAnson** [comment]
Please try version 0.8.1 and let me know if you still see a problem.

**Comment by stevemart** [comment]
@DavidAnson worked like a charm!

```
smartinelli-mac howtos $ markdownlint --version
0.8.1
smartinelli-mac howtos $ markdownlint --config .markdownlint.json `ls -d */ | grep -v 'node_modules/'`
```

Thanks so much for the quick turn around and your contribution to this project in general :)

**Comment by DavidAnson** [comment]
You bet. :)
