### ISSUE TITLE
Support for Language Server Protocol

### ISSUE THREAD

**Issue by JannoTjarks** [igorshubovych/markdownlint-cli#350]
Hi, first of all. Thank you very much for this project.

Would it be possible to add support for the [language-server protocol](https://microsoft.github.io/language-server-protocol/)? Then it would be easy to use the tool inside vim/neovim/emacs/JetBrains/... with the standard way.

My dream would be a command line argument like --language-server.

Greetings from the North of Germany!

**Comment by JannoTjarks** [comment]
Hi @DavidAnson, from my point of view the advantages would be, that it would be possible to send errors/warnings to the editor for each rule, which is broken by the markdown file.
At the moment i need to leave my editor or use markdownlint in a specific tab.

This could be handled by a LSP. One example from errors in the language go. 
![image](https://user-images.githubusercontent.com/33316737/211357191-712199fb-40ed-4eb5-9b00-9cd8dabf4b78.png)

Maybe there is already something like this based on the language server protocol. I saw already something based on coc but this cannot used by other editors AFAIK.

**Comment by DavidAnson** [comment]
I've written an extension for VS Code and there are other integrations, including coc, here: https://github.com/DavidAnson/markdownlint#related

I'm happy if someone wants to create an LSP, but I think that would be most appropriate as a separate project.

**Comment by JannoTjarks** [comment]
Hi David, thank you very much. Hopefully I will find some time by my own to create a LSP!
