### ISSUE TITLE
Bug in markdownlint when using .markdownlintignore with folder with many lint issues.

### ISSUE THREAD

**Issue by acartag7** [igorshubovych/markdownlint-cli#359]
Hello, 

I've been getting this bug recently when we added markdownlint to our pipelines and tried to ignore a big folder with `.markdownlintignore` file. The situation with this is that when running markdownlint without the ignore file, it runs correctly and shows the lines to fix, but whenever I run it with the `.markdownlintignore` file it shows many executions like in the screenshot and exits with code 0.

The folder I am trying to ignore has around 1k+ lines to fix, so maybe that's why it crashes when trying to ignore it.

<img width="1073" alt="Screenshot 2023-02-03 at 09 28 30" src="https://user-images.githubusercontent.com/24943480/216550067-20eb702b-5c76-4a07-b228-6d25fe9dacfe.png">

**Comment by Spacetown** [comment]
For me this is related to your xargs command. Can you post the full command line?

**Comment by awca22** [comment]
Here is what I found out:

Basically what the xargs command is doing something similar to this:
```bash
root [ /api]# markdownlint -c scripts/config/markdownlint.yml new-service-rest/go-client/docs/README.md
Usage: markdownlint [options] <files|directories|globs>

MarkdownLint Command Line Interface

Options:
  -V, --version                               output the version number
  -c, --config [configFile]                   configuration file (JSON, JSONC, JS, or YAML)
  -d, --dot                                   include files/folders with a dot (for example `.github`)
  -f, --fix                                   fix basic errors (does not work with STDIN)
  -i, --ignore [file|directory|glob]          file(s) to ignore/exclude (default: [])
  -j, --json                                  write issues in json format
  -o, --output [outputFile]                   write issues to file (no console)
  -p, --ignore-path [file]                    path to file with ignore pattern(s)
  -q, --quiet                                 do not write issues to STDOUT
  -r, --rules  [file|directory|glob|package]  include custom rule files (default: [])
  -s, --stdin                                 read from STDIN (does not work with files)
  --enable [rules...]                         Enable certain rules, e.g. --enable MD013 MD041 --
  --disable [rules...]                        Disable certain rules, e.g. --disable MD013 MD041 --
  -h, --help                                  display help for command
```

If the file im passing to check in this case `new-service-rest/go-client/docs/README.md` is included on the path I'm currently ignoring in `.markdownlintignore`, it seems like it is empty and doesn't do anything. That is my best guess.

I guess I'll probably run it only using `markdownlint -c scripts/config/markdownlint.yml .` and not using a find to pass the specific files but instead all the repository directory.

**Comment by DavidAnson** [comment]
Issue #104 seems relevant here. If so, your idea should help.
