### ISSUE TITLE
Add a summary at the end

### ISSUE THREAD

**Issue by Spacetown** [igorshubovych/markdownlint-cli#360]
Hi,
if running the tool with the current working directory `markdownlint --ignore __pycache__ --ignore repos/ --config /etc/markdownlint.yml .` and there are no errors the output is empty. This is the same when running the command for a directory where no files are found. It would be nice to have a summary (maybe controlled by an option) at the end, e.g.:

```
Markdownlint: Files checked: 50, Issues found: 0 in 0 files
```

Than you can be sure that there was something checked.

For bigger repositories als a progress indication would be nice:

```
 1/50 file1.md 2623.52ms
 2/50 ./doc/file2.md 174.05ms
...
```

**Comment by DavidAnson** [comment]
Duplicate of #49, available in CLI2.

**Comment by Spacetown** [comment]
Sorry, I've checked only summary and not statistics.
