### ISSUE TITLE
Allow including a custom rule via package name

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [igorshubovych/markdownlint-cli#42]
This works right now:

```cmd
markdownlint --config .markdownlint.json --rules ./node_modules/sentences-per-line/index.js README.md
```

...but this does not:

```cmd
markdownlint --config .markdownlint.json --rules sentences-per-line README.md
```

Relevant function: `prepareFileList`

**Comment by DavidAnson** [comment]
I think this should work if the custom rule’s `package.json` is correct. Here is the test case for it: https://github.com/igorshubovych/markdownlint-cli/blob/master/test/test.js#L381

Can you share the `package.json` for your scenario?

**Comment by JoshuaKGoldberg** [comment]
Sure: https://github.com/JoshuaKGoldberg/sentences-per-line/blob/6a99e70507129baa80bbca4f2b754ee972b18789/package.json

**Comment by DavidAnson** [comment]
Thanks, that looks okay from my phone. Will need to investigate.

**Comment by DavidAnson** [comment]
Fixed by @VeselovAlex
