### ISSUE TITLE
Requesting new version

### ISSUE THREAD

**Issue by Mister-Hope** [igorshubovych/markdownlint-cli#424]
I encountered CJK characters anchor problem with markdownlint@0.30.0, and this has been fixed in 0.31.0

It would be nice if you can release a new version to raise markdownlint to 0.31.0 so that I can pass my ci linter test again.

**Comment by silverwind** [comment]
Waiting on this as well.

**Comment by DavidAnson** [comment]
`0.37.0` is now available.
