### ISSUE TITLE
Allow failure in combination with --fix

### ISSUE THREAD

**Issue by Finkregh** [igorshubovych/markdownlint-cli#425]
I'm using markdownlint in combination with pre-commit. Currently if there is something to fix mdl will exit with 0. Is there some flag that i did not see which changes this behaviour?

**Comment by DavidAnson** [comment]
Exit code 0 means there were no violations at the end of the run. That includes the scenario where there were violations but they were fixed by the tool. That sounds like your scenario based on the issue title. If you want exit code 1 in that case, you can remove the --fix parameter.

**Comment by Finkregh** [comment]
I'd like to have both, as pre-commit does not stop with "some tool did changes, please go back and edit your commit" with this behaviour :)

**Comment by DavidAnson** [comment]
If you are going to go back and edit the commit anyway, you can get the error by not passing `--fix`. If you want to fix in pre-commit then detect changed files in git, you can do so with `git diff --exit-code`.
