### ISSUE TITLE
Custom rules

### ISSUE THREAD

**Issue by cakoolen** [igorshubovych/markdownlint-cli#433]
I'm trying to configure markdownlint-cli such that it checks the rules such that we can use mkdocs to generate html from markdown without it being a hit-and-miss. According to it's documentation lists (ordered and unordered) should use 4 spaces or a tab as indentation. For unordered lists there is a rule readily available though for ordered lists this does not exist. Can I use a custom rule to check this?

**Comment by DavidAnson** [comment]
Yes

**Comment by DavidAnson** [comment]
https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md
