### ISSUE TITLE
Unable to pull container image

### ISSUE THREAD

**Issue by niall-byrne** [igorshubovych/markdownlint-cli#438]
First of all, thanks for creating this package.

Sadly, over the past few hours, I have been unable to pull the container ghcr.io/igorshubovych/markdownlint-cli to my local machine.  Interestingly, in workflows that consume the container, it is still able to be used.

Is there any chance the permissions have changed on the repository images?

Thanks again for creating this!

**Comment by DavidAnson** [comment]
There have been no permission changes on my side. Additionally, the example Docker command in README.md works for me when run locally, including pulling the latest image.

**Comment by niall-byrne** [comment]
Thanks for getting back to me!  I'm sorry I didn't realize this sooner but it's all containers on ghcr.io, so it has to be a local config issue.
