### ISSUE TITLE
Pre-commit run against staged files only

### ISSUE THREAD

**Issue by jsburckhardt** [igorshubovych/markdownlint-cli#441]
Quick question. I'm using the pre-commit config in my repo. It works great! But I'm not sure if I'm doing something wrong in the configuration because it is running the check against all the files. Is that the expected behaviour? I was expecting it to check only staged files. Cheers.

**Comment by DavidAnson** [comment]
The list of files you pass to the tool are up to you. This workflow does what you want and may be helpful to review: https://github.com/DavidAnson/markdownlint-cli2-action/blob/main/.github/workflows/changed.yml
