### ISSUE TITLE
Bug: '-r' parameter does not work with scoped package 

### ISSUE THREAD

**Issue by BolkoSchreiber** [igorshubovych/markdownlint-cli#449]
`markdownlint -r @myScope/custom_rules_package .` does not work. 

error msg:
> Cannot load custom rule @myScope/custom_rules_package: No such rule

workaround:  
install scoped package locally and change cli call to 
> markdownlint -r node_modules/@myScope/custom_rules_package .

**Comment by DavidAnson** [comment]
Glancing at the code, I think `tryResolvePath` is incorrectly deciding this is a file path based on having a slash in it.
