### ISSUE TITLE
Disable rule with parameters 

### ISSUE THREAD

**Issue by ruzickap** [igorshubovych/markdownlint-cli#452]
I'm trying to disable the "Line length" [MD013](https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md#md013---line-length) with `tables=false` parameter, but I'm not sure how to do it using command line `--disable ...`.

Is there any way how to do it? 

Something like `markdownlint-cli --disable MD013.tables=false` ?

Thank you...

**Comment by DavidAnson** [comment]
If you want to disable a rule entirely, you can do that on the command line. However, if you want to configure a rule, you need to do so with a configuration file like .markdownlint.json or a configuration comment in any relevant Markdown file.

**Comment by ruzickap** [comment]
It means - the `markdownlint-cli` does not support `--disable` cli parameter to disable rule with parameters.
Only entire "rule" can be disabled.
Thank you...

**Comment by paddyroddy** [comment]
Just to voice my opinion on this, I am setting some organisation default `pre-commit` hooks (which the maintainer isn't a fan of, but anyway). This works well with something like `yamllint`, i.e. https://github.com/paddyroddy/.github/blob/01b21d364696c33e4df82c92f9dfefc6a2b6f6f6/precommit/general/general-hooks.yml#L3-L47. It would be great if it was possible to do this with `markdownlint-cli` too.

**Comment by DavidAnson** [comment]
@paddyroddy It is possible to configure rules today, just not on the command line. You've already said the maintainer of your project doesn't favor that approach and I agree. The example you link to will report failures at commit time, but people will have no easy way to run that same command directly to figure out what's going on. If, instead, the configuration were in a file, then simply invoking the command by name would automatically apply the same set of rules that used by the commit hook. I suggest this is easier and more productive for the team.

**Comment by paddyroddy** [comment]
I appreciate my application is niche @DavidAnson, but it does basically mean I have to have a `.markdownlint.yaml` in every repo that I want it in - if I were to just disable tables for `MD013`.
