### ISSUE TITLE
Idea: adding selective ignore

### ISSUE THREAD

**Issue by 403-html** [igorshubovych/markdownlint-cli#494]
# Idea

I see that there's ignore file, but it's for ignoring files to be linted, but there are just parts of files which are "incompatible" but in fact we want to ignore this rule just for given line, so that'd be helpful

## Example use

It could use the same ignoring pattern as with disabling whole rule in given file (`markdownlint-disable MD033`), but for next line (markdownlint-disable next), so it could be like this for violating `MD022/blanks-around-headings` just in given line

```md
<!-- markdownlint-disable next -->
# Header
Text
```

**Comment by DavidAnson** [comment]
This is already supported by the library: https://github.com/DavidAnson/markdownlint?tab=readme-ov-file#configuration

I will reference that from the documentation.

**Comment by 403-html** [comment]
wow... I missed that so hard, sorry then
