### ISSUE TITLE
[feature request] .markdownlintignore

### ISSUE THREAD

**Issue by jjangga0214** [igorshubovych/markdownlint-cli#61]
What if we have the file like **.markdownlintignore**?
Listing all directories and files to ignore on single command might be somewhat improper in some cases. (And I even avoid using a shorthand option like `-i` to let people understand the option more easily)
```bash
{
# - A few directories (e.g. node_modules) which contains external markdown files. 
# - A few directories (e.g. .git) which does not actually contain markdown files, 
#   but should be ignored for performance as they are 'deep' and 'wide'. 
# - A few exceptional markdown files (e.g.CHANGELOG.md) 
#   that has some special reasons to be ignored (e.g. written and managed by machine)
  "lint:md": "markdownlint --ignore node_modules --ignore .git --ignore CHANGELOG.md --ignore ..."
}
```

In those cases, the script specifed in package.json would be so long, leading a bit of inconvenient experience.

How do you feel?

**Comment by fboutin-pmc** [comment]
I really miss that feature.

If you compare with eslint - https://eslint.org/docs/user-guide/configuring#eslintignore

My `.eslintignore` file looks like,
```
/content
/public
/node_modules
/coverage
dist/
/themes
```

But with this linter I have to do something like: 

```sh
markdownlint --ignore content --ignore public --ignore node_modules --ignore coverage --ignore dist --ignore themes
```

My point is: I think it is a bit more important than a simple "enhancement".

**Comment by DavidAnson** [comment]
“Enhancement” seems like the most relevant default label for a feature request. I think you would agree the others are all worse. :)
