### ISSUE TITLE
MD022 with --fix changing wrong lines

### ISSUE THREAD

**Issue by nschonni** [igorshubovych/markdownlint-cli#67]
I know this isn't actually released yet, but I was trying it out from installing it from the current tarball.

Steps to reproduce:
1. Clone https://github.com/dotnet/docs
1. Remove the "MD022" suppression in .markdownlint.json
1. Run `markdownlint --fix "docs/visual-basic/**/*.md"` (just to minimize the affected files

Expected Result:
Newlines around/after the ATX headings

Actual Result:
Newlines after opening frontmatter and in lists

Might give you a nice test bed for kicking the tires on the `--fix`.

**Comment by DavidAnson** [comment]
Good to know, thanks! I was going to release tomorrow, but fixing this issue will probably require an update to the core library first. Let me know if you spot any other problems!

**Comment by DavidAnson** [comment]
Can you easily show a file name or two with examples? I won’t be able to try this until tonight - but I can think about it all day. :)

**Comment by DavidAnson** [comment]
Ouch, looks like the fix helper methods don't know to ignore YAML frontmatter, so apply their changes to the wrong place in files that contain it.

**Comment by DavidAnson** [comment]
It's not looking that dramatic after all - fixes that include line number overrides aren't adjusting for frontmatter. I'll fix this in the core library.

**Comment by nschonni** [comment]
Great! glad you sorted it out

**Comment by DavidAnson** [comment]
Fixed in the core library: https://github.com/DavidAnson/markdownlint/commit/9202ebe39042d586aa461e80df7da3ac7691bd3a

New release on the way...

**Comment by DavidAnson** [comment]
Fixed by https://github.com/igorshubovych/markdownlint-cli/commit/ac31a8aa9d482e956c74382c47ce47af77b36818

The output of your scenario above now appears to be correct.
