### ISSUE TITLE
Versioning of output format

### ISSUE THREAD

**Issue by pascalberger** [igorshubovych/markdownlint-cli#71]
Writing issues to a file using the `--output` command is useful for processing the issues further. Currently there's no versioning for the output format though. Changes like https://github.com/igorshubovych/markdownlint-cli/pull/64 might break code which parses the output format. Therefore it would be nice to have the output format containing a version number, which would make parsing of the result easier.

**Comment by DavidAnson** [comment]
This change seems unnecessary if #58 is implemented to output into a standard format.

**Comment by DavidAnson** [comment]
Closing this in favor of #58 per above comment.
