### ISSUE TITLE
parsing of markdownlintrc fails because of comments(?)

### ISSUE THREAD

**Issue by Stanzilla** [igorshubovych/markdownlint-cli#72]
Currently when run via the CLI as `npx markdownlint src/ --config .markdownlintrc` the script fails with 

```
Cannot read or parse config file .markdownlintrc: Unable to parse '.markdownlintrc'; Unexpected token / in JSON at position 169; missed comma between flow collection entries at line 10, column 12:
        "MD046": false,
               ^
```

is there a way this could be fixed by switching to a JSON5 compatible parser or maybe just strip them out instead of failing?

Content of `.markdownlintrc`
```
{
    // Enable all markdownlint rules
    "default": true,

    // Disable line length check for tables and code blocks
    "MD013": { "line_length": 180, "code_blocks": false, "tables": false },

    // Set Ordered list item prefix to "ordered" (use 1. 2. 3. not 1. 1. 1.)
    "MD029": { "style": "ordered" },

    // Set list indent level to 4 which Python-Markdown requires
    "MD007": { "indent": 4 },

    // Exclude code block style
    "MD046": false,
    "no-alt-text": true,
    "no-inline-html": false,
    "no-space-in-code": false,
    "code-block-style": "consistent"
}
```

**Comment by alexrp** [comment]
@DavidAnson I don't believe this is fully fixed. I have a `.markdownlintrc` with a single comment at the top and this seems to cause `markdownlint-cli` (0.26.0) to silently fail to read the file. If I explicitly pass `--config .markdownlintrc` or remove the comment, everything works fine.

**Comment by DavidAnson** [comment]
@alexrp Could you please point to a repo that demonstrates this or share the relevant files here? (The fact that it works with `--config` suggests this issue to allow comments in the file is working correctly.)

**Comment by alexrp** [comment]
It might actually be an `rc` issue.

```
$ cat > test.md <<EOF
> # Test
>
> # Test 2
> EOF
$ cat > .markdownlintrc <<EOF
> # This is a comment.
>
> { "MD025": false }
> EOF
$ markdownlint test.md
test.md:3 MD025/single-title/single-h1 Multiple top level headings in the same document [Context: "# Test 2"]
$ markdownlint --config .markdownlintrc test.md
$
$ sed -i '1d;2d' .markdownlintrc
$ markdownlint test.md
$
```

My suspicion is that `rc` skips over the file due to the comment.

**Comment by nschonni** [comment]
`#` isn't a comment character for JS/JSON, just Yaml. I'm guessing since the rest of the file looks like JSON, RC wouldn't recoginize that as a comment at all. Maybe try `//` if you want comments

**Comment by alexrp** [comment]
The issue exists with both `#` and `//`. (Actually, the case where I ran into the issue was using `//`, not sure why I used `#` here...)

**Comment by DavidAnson** [comment]
I think by putting the comment at the top, you may be breaking `rc`'s logic to detect JSON/INI: https://github.com/dominictarr/rc/blob/master/lib/utils.js#L9-L12
