### ISSUE TITLE
Add non-zero return code when issues found

### ISSUE THREAD

**Issue by briggySmalls** [igorshubovych/markdownlint-cli#75]
Many linters will use the return code to indicate if there were issues found with the source.

This makes them easily integrated into a CI pipeline, where any non-zero return codes indicate the job has failed.

markdownlint-cli would be more useful to me if it implemented such a return code

**Comment by DavidAnson** [comment]
It already does so: https://github.com/igorshubovych/markdownlint-cli/blob/6c13911af8dfec6baa7c0559c7d4ca959c3d451f/markdownlint.js#L148

What is your scenario and what return value are you seeing? Or are you asking to make a note of this in the README?

**Comment by briggySmalls** [comment]
Oh blimey. I'm very sorry. Too much haste.

I think it's because I was trying to pipe the result into word count (`markdownlint content | wc`) and got neither a word count nor a return code.

But this issue is incorrect. Sorry to waste your time.

**Comment by DavidAnson** [comment]
Glad you got this sorted!

**Comment by arvigeus** [comment]
What about disabling this behavior for the cases where issues are considered only warnings? Related: [markdownlint#254](https://github.com/DavidAnson/markdownlint/issues/254)

**Comment by DavidAnson** [comment]
Agreed, if/when warnings are introduced, the behavior of exit code should be considered.
