### ISSUE TITLE
upgrade to v0.19.0 of markdownlint

### ISSUE THREAD

**Issue by ljharb** [igorshubovych/markdownlint-cli#76]
v0.19 fixes an off-by-one error in MD007.

**Comment by DavidAnson** [comment]
Already done, it’ll be part of the next release in a few days: https://github.com/igorshubovych/markdownlint-cli/blob/6c13911af8dfec6baa7c0559c7d4ca959c3d451f/package.json#L49

**Comment by ljharb** [comment]
Awesome, thanks :-) I’ll wait for the release.
