### ISSUE TITLE
MD034 does not recognize GitBook syntax

### ISSUE THREAD

**Issue by mikyjpeg** [igorshubovych/markdownlint-cli#78]
## Description
I've an md file which is using a gitbook plugin to integrate video.

the integration works adding the following line:

`{% youtube src="https://www.youtube.com/watch?v=SHOVVnRB4h0" %}{% endyoutube %}`

When running the markdownlint I got a MD034, but that's actually a valid code. I can't find another way than disabling MD034, which I'd prefer not to do. Any suggestion?

### Environment
I'm using markdownlint-cli 0.22.0 with node 12.12.0

### Expected Behavior
MD034 shouldn't be raised

### Actual Behavior
it's raised

## Replication Case
copy the line above into a markdown file and execute the linting

**Comment by DavidAnson** [comment]
The rule is correct; the syntax above is not part of Markdown and receives no special treatment. What I may be able to do to help here is add a parameter `ignore_quoted` which would tell the rule not to report in this (and similar) situations.

**Comment by mikyjpeg** [comment]
Thanks, David I understand. I was surpised because I thought it was quite used with gitbook and this doesn't look an extreme case. I was wondering, is there a workaround to skip a specific line or block to avoid disabling the entire rule?

**Comment by DavidAnson** [comment]
Yes, there are examples here: https://github.com/DavidAnson/markdownlint/blob/master/README.md#configuration

**Comment by DavidAnson** [comment]
This is allowed by https://github.com/DavidAnson/markdownlint/commit/320acfd7cc02d02bf6c1c941c01f59bbfbc97cca for the next release.

**Comment by DavidAnson** [comment]
Relevant build referenced by https://github.com/igorshubovych/markdownlint-cli/commit/6e4fa47d2978403ec4eb2c8f995b7b2dcec4e84e for the next release of the CLI.
