### ISSUE TITLE
Fix for MD031 in blockquotes doesn't add > character

### ISSUE THREAD

**Issue by nschonni** [igorshubovych/markdownlint-cli#82]
When fixing the space around code fences, if the code fence is inside a blockquote, it still just adds a blank line. This will cause a separate violation for blank lines in blockquotes. The `--fix` should also add the `>` at the correct indent level.

**Comment by DavidAnson** [comment]
Fixed in the library for the next release: https://github.com/DavidAnson/markdownlint/commit/e319f9501c111cbf54839929692ab7a01d473cdc

**Comment by DavidAnson** [comment]
Relevant build referenced by https://github.com/igorshubovych/markdownlint-cli/commit/6e4fa47d2978403ec4eb2c8f995b7b2dcec4e84e for the next release of the CLI.
