### ISSUE TITLE
Is there / could there be an easy way to run continually?

### ISSUE THREAD

**Issue by mrmanc** [igorshubovych/markdownlint-cli#87]
I’m looking into whether we can get this running continually alongside mkdocs when developing locally. I think I can do it using a scheduler container to invoke a markdownlint-cli container, but I wanted to ask if there was an easier / more efficient way of doing this using markdownlint-cli itself.

**Comment by DavidAnson** [comment]
I’m not sure I understand the scenario. Are you looking to add it to an “watch“ command, similar to how web developers will automatically update their build as they change source files? If so, I’m not sure anything about the CLI needs to change; you could invoke it from a script like that today.

**Comment by mrmanc** [comment]
I wondered about using watch but it’s time-based, so still not ideal. Ideally, it would run when it detects changes, not just every five or so seconds—I think that would just create noise in the terminal. I’m having a go with watch, but I might need to get someone else to help as my container is just exiting with status 0 as soon as the command is invoked. Weird, as it runs properly when I shell in and run it manually. I did spot [Watchman](https://facebook.github.io/watchman/) which looks like it can run commands when files change.

**Comment by DavidAnson** [comment]
In my experience, a typical watch in Node is based on file changes. See, for example: https://www.npmjs.com/package/npm-watch

**Comment by mrmanc** [comment]
Thanks. I got a version working with inotifyd but I get multiple events (possibly due to temporary files) which causes me to scan twice for each edit. I found nodemon and have got it doing what I wanted… seems to work better so I’m going to containerise it. When you first mentioned watch, I was thinking UNIX watch, which is why I’d discounted it.

**Comment by DavidAnson** [comment]
Great! I'll close this issue as it doesn't seem like a change is needed to the package.
