### ISSUE TITLE
Auto fix for MD034 includes trailing punctuation

### ISSUE THREAD

**Issue by nschonni** [igorshubovych/markdownlint-cli#89]
I've noticed on some links, the fix for the bare URLs sometimes includes trailing punctuation like `, ) .` that aren't included with the auto-URL rendering. Not sure if there is a list that could be ignored for those based on what GHM already ignores at the end of URLs

Examples:
- `Some text then https://example.com, continuing text` becomes `Some text then <https://example.com,> continuing text`
- `Some text (then https://example.com)` becomes `Some text then <https://example.com)>`
- `Some text then https://example.com.` becomes `Some text then <https://example.com.>`

**Comment by DavidAnson** [comment]
Agreed - do you mind opening this issue against the core library instead? I can't transfer it due to the different owner.

**Comment by nschonni** [comment]
Opened over on the core repo. Did you want me to close this one?

**Comment by DavidAnson** [comment]
Thank you.
