### ISSUE TITLE
Version 0.23.0 - MD037 - Need to escape underscore character inside bold tag

### ISSUE THREAD

**Issue by gcbeltramini** [igorshubovych/markdownlint-cli#94]
Version 0.23.0 changed the behavior of the test for `MD037`. I have to start escaping the underscore character inside the bold tag. Was that intentional?

```bash
$ markdownlint --version
0.23.0

$ cat foo.md
# Foo

**foo_bar**, *baz*

$ markdownlint foo.md
foo.md:3:1 MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "**foo_bar**, *"]
```

If the `_` character is escaped, the test passes:

```bash
$ cat foo.md
# Foo

**foo\_bar**, *baz*

$ markdownlint foo.md
```

It works in both cases in version 0.22:

```bash
$ sudo npm install -g markdownlint-cli@0.22
(...)

$ markdownlint --version
0.22.0

$ cat foo.md
# Foo

**foo\_bar**, *baz*

$ markdownlint foo.md

$ cat foo.md
# Foo

**foo_bar**, *baz*

$ markdownlint foo.md
```

**Comment by DavidAnson** [comment]
This is a bug in the `markdownlint` library, first identified here: https://github.com/dotnet/docs/pull/18269#issuecomment-624418381

**Comment by DavidAnson** [comment]
This is fixed by https://github.com/DavidAnson/markdownlint/commit/f607a49a5bd4c8d8dae635a8de4ad6a27fee3dc5 for the next (patch) release of the library/CLI.

Thanks for the great issue!

**Comment by gcbeltramini** [comment]
Thanks for the quick fix!

**Comment by DavidAnson** [comment]
Fixed in 0.23.1

**Comment by nschonni** [comment]
Found one that's still hitting after installing the latest https://github.com/MicrosoftDocs/iis-docs/blob/6f3b6fb492d7b76ff12d33db587c74bf9990bcf6/iis/web-dev-reference/server-variables.md#L60

for this line

```
| LOGON_USER            | The Windows account that the user is impersonating while connected to your Web server. Use **REMOTE_USER**, **UNMAPPED_REMOTE_USER**, or **AUTH_USER** to view the raw user name that is contained in the request header. The only time LOGON_USER holds a different value than these other variables is if you have an authentication filter installed. |
```

**Comment by DavidAnson** [comment]
@nschonni What’s happening here is that the `_` in the very first cell is being treated as the start of an emphasis which ends with the following `_`, so the `**` after look mismatched as the rule reports.

I could maybe fix this by recognizing that it occurs within a table context and then treating the `|` as delimiters. If you’d like to open a bug against the library, I will look at this for a future release. I don’t think it merits a patch release.

Thanks!

**Comment by DavidAnson** [comment]
@nschonni Actually, this is always going to be a risk because this rule is more liberal about what it accepts versus the official Markdown specification. Your example happens to be fixable by recognizing the table, but that’s just luck. I’m not sure there is a good general purpose fix for this scenario because it’s part of this rule trying to detect misuse and therefore being more permissive about what it thinks can start and end an emphasis.
