### ISSUE TITLE
MD044 throws exception for specific content

### ISSUE THREAD

**Issue by alexbuckgit** [igorshubovych/markdownlint-cli#98]
When the following configuration for MD044:

"MD044": {
        "code_blocks": false,
        "names": 
        [ 
            "Test"
        ]
    }

With a markdown file containing this line:

**test-noreply\@mydomain.com**

The following exception is thrown:

C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\lib\markdownlint.js:762
      throw error;
      ^

Error: Property 'range' of onError parameter is incorrect.
    at throwError (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\lib\markdownlint.js:465:13)
    at onError (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\lib\markdownlint.js:494:9)
    at addError (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\helpers\helpers.js:410:3)
    at addErrorDetailIf (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\helpers\helpers.js:424:5)
    at token.content.split.forEach (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\lib\md044.js:44:19)
    at Array.forEach (<anonymous>)
    at forToken (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\lib\md044.js:25:12)
    at forChild (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\helpers\helpers.js:299:9)
    at Array.forEach (<anonymous>)
    at forToken (C:\Users\bob\AppData\Roaming\npm\node_modules\markdownlint-cli\node_modules\markdownlint\helpers\helpers.js:297:20)

**Comment by alexbuckgit** [comment]
The issue is actually more severe and destructive that I first realized.

If I include ".NET" as a value in the MD044 names parameter, then run markdownlint at the command line with the --fix parameter on a file containing this line:

    Check (**myserver.mydomain.net**) for failure.

It replaces the entire parenthetical phrase, like this:

   Check (**.NET**) for failure.

**Comment by DavidAnson** [comment]
It looks like you are reporting two different issues here. The first is an exception and the second is an incorrect fix. Could you please open a separate issue for the latter?

**Comment by DavidAnson** [comment]
Regarding the exception, I do not see that in a simplified example based on what you describe above. Could you please check if there is something else in the file or surrounding markup that is necessary to reproduce this? Or link to the file that shows the problem?

https://dlaa.me/markdownlint/#%25m%23%20Issue%2098%0A%0Atest-noreply%40mydomain.com%0A%0A%3C!--%20markdownlint-configure-file%20%7B%0A%20%20%22MD044%22%3A%20%7B%0A%20%20%20%20%22code_blocks%22%3A%20false%2C%0A%20%20%20%20%22names%22%3A%20%5B%0A%20%20%20%20%20%20%22Test%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D%20--%3E%0A

**Comment by DavidAnson** [comment]
The incorrect application of the fix (your second comment above that I'd like moved to a new issue in the <https://github.com/DavidAnson/markdownlint> repo) reproduces for me in this sample document. I'll look into it for the next release of the library.

```md
# Issue 98-2

Check (**myserver.mydomain.net**) for failure.

<!-- markdownlint-configure-file {
  "MD044": {
    "code_blocks": false,
    "names": [
      ".NET"
    ]
  }
} -->
```

**Comment by alexbuckgit** [comment]
The exception occurs from the command line when a backslash appears before the @ symbol. It's doesn't fail when I try from the markdownlint demo website.

test\@mydomain.com

**Comment by alexbuckgit** [comment]
Unfortunately, GitHub is reformatting my example when I submit the comment.

The example should be:

test<BACKSLASH_CHARACTER_HERE>@mydomain.com

**Comment by alexbuckgit** [comment]
or:
test/@mydomain.com

But replace the forward slash with a back slash.

**Comment by DavidAnson** [comment]
I'm not seeing a crash. Have I set up the scenario correctly? Can you point me to a file that reproduces the problem? I'm happy to narrow it down from there.

```bash
pi@pi:~/cli-issue-98 $ node --version
v14.4.0
pi@pi:~/cli-issue-98 $ npm ls --depth 0
/home/pi/cli-issue-98
└── markdownlint-cli@0.23.1

pi@pi:~/cli-issue-98 $ cat example.md 
# Issue 98

test\@mydomain.com

<!-- markdownlint-configure-file {
  "MD044": {
    "code_blocks": false,
    "names": [
      "Test"
    ]
  }
} -->
pi@pi:~/cli-issue-98 $ ./node_modules/.bin/markdownlint example.md 
example.md:3 MD044/proper-names Proper names should have the correct capitalization [Expected: Test; Actual: test]
pi@pi:~/cli-issue-98 $
```

**Comment by alexbuckgit** [comment]
I updated my node and npm versions and the issue no longer occurs. Thanks!
